---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "assets/Leap_Second.dat"
      - id: pretty-format-json
        args: ["--autofix"]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        exclude: "assets/Leap_Second.dat"
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.10.0
  #   hooks:
  #     - id: hadolint-docker
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.45.2
    hooks:
      - id: golangci-lint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-mod-tidy
      - id: go-unit-tests
      - id: go-build
