---
name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get Go version from go.mod
        id: get-go-version
        shell: bash
        run: |
          sed -En 's/^go (.*)$/go-version=\1/p' go.mod >> $GITHUB_OUTPUT

      - name: Set up Go version ${{ steps.get-go-version.outputs.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.get-go-version.outputs.go-version }}

      - name: Restore Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: Check for data races
        run: make race

      - name: Benchmark
        run: make benchmark
